### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [mattmarch/smartalarmclock#1]
Hello @mattmarch I contribute to the open source community by designing logos. I have a nice idea that represents the function of the project. I can design it if you want and i show it. I will wait for feedback. Have a nice day.

**Comment by mattmarch** [comment]
Hi @reallinfo, firstly thanks for your offer and sorry for the slow response! However as this is just a very small hobby project I'm going to say we don't need a logo (at least yet!).
